/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financeapp;

import java.time.Month;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aahughes
 */
public class DataViewScreen extends javax.swing.JPanel {
    
    AppFrame frame;
    Month currentMonth;
    int monthIndex;
    String totalAmount;
    String totalBalance;
    
    /**
     * Creates new form DataViewScreen
     * @param theframe
     */
    public DataViewScreen(AppFrame theframe) {
        this.frame = theframe;
        
        currentMonth = BudgetController.currentMonth;
        monthIndex = currentMonth.getValue() - 1;
        frame.controller.updateMonth();
        
        initComponents();
        updateTableModel(getBudgetListByMonth(currentMonth));
        setTotalAmountandBalance(currentMonth);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeFrameList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        totalBalanceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalAmountField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        timeFrameList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        timeFrameList.setSelectedIndex(monthIndex);
        timeFrameList.setSelectedItem(currentMonth.toString());
        timeFrameList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFrameListActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Budget Balance:");

        totalBalanceField.setText(totalBalance);

        jLabel6.setText("Total Budget Amount:");

        totalAmountField.setText(totalAmount);
        totalAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(" Monthly Budgets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(timeFrameList, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeFrameList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timeFrameListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFrameListActionPerformed
        String selected = timeFrameList.getSelectedItem().toString();

        Month selectedMonth = Month.valueOf(selected);
        
       
        updateTableModel(getBudgetListByMonth(selectedMonth));
        setTotalAmountandBalance(selectedMonth);
    }//GEN-LAST:event_timeFrameListActionPerformed

    private ArrayList<Budget> getBudgetListByMonth(Month selectedMonth){
        MonthlyBudget budgets = frame.controller.getMonthlyBudget(selectedMonth);
        
        ArrayList<Budget> budgetList = new ArrayList();
        
        if (budgets != null)
            budgetList = budgets.getBudgetList();
        
        return budgetList;
    }
    
    private void setTotalAmountandBalance(Month month){
        MonthlyBudget currentBudget = frame.controller.getMonthlyBudget(month);
        if (currentBudget != null){
            totalAmount = Double.toString(currentBudget.getTotalBudget().getAmount());
            totalBalance = Double.toString(currentBudget.getTotalBudget().getBalance());
        }
        else{
            totalAmount = "---";
            totalBalance = "---";
        }     
        totalAmountField.setText(totalAmount);
        totalBalanceField.setText(totalBalance);
    }
    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        frame.openMenu();
    }//GEN-LAST:event_backButtonActionPerformed

    private void totalAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountFieldActionPerformed

public void updateTableModel(ArrayList<Budget> budgetList){
        //Create new table model
        DefaultTableModel tableModel = new DefaultTableModel();

        int columnCount = 3;
        
        
        tableModel.addColumn("Name");
        tableModel.addColumn("Amount");
        tableModel.addColumn("Balance");
        
        tableModel.setRowCount(budgetList.size());
        int row = 0;
        //Scroll through transactions
        
        for (Budget b : budgetList){
            tableModel.setValueAt(b.getCategory(), row, 0);
            //debug
            System.out.println(b.getCategory());
            
            tableModel.setValueAt(b.getAmount(), row, 1);
            tableModel.setValueAt(b.getBalance(), row, 2);
            row++;
        }

        //Now add that table model to your table and you are done :D
        table.setModel(tableModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JComboBox timeFrameList;
    private javax.swing.JTextField totalAmountField;
    private javax.swing.JTextField totalBalanceField;
    // End of variables declaration//GEN-END:variables
}
